// ===============================================================
// export function formatDate(isoString) {
//   const date = new Date(isoString);

//   // Extract date components
//   const day = date.getDate();
//   const month = date.toLocaleString("default", { month: "short" }); // Use "short" for 3-letter month
//   const year = date.getFullYear();

//   // Create a readable date string
//   return `${month} ${day}, ${year}`;
// }

// ===========================================================
export const convertDatetoString = (dateString) => {
  // Parse the input date string
  if (!dateString) {
    return "";
  }
  const [year, month, day] = dateString.split("-").map(Number);
  const date = new Date(Date.UTC(year, month - 1, day, 18, 30, 0)); // Set time to 18:30:00 UTC

  // Convert to ISO 8601 format
  return date.toISOString();
};
// date now =================================================
export const getCurrentDateInISOFormat = () => {
  return new Date().toISOString();
};

// dd/mm/yyyy to string ======================j
export const convertToDateTimeString = (dateStr) => {
  const [day, month, year] = dateStr.split("/");
  const date = new Date(year, month - 1, day); // Months are 0-indexed in JS

  return date.toISOString(); // This returns the date in ISO format
};

// ========================== for digit two round up ==================================
export function formatDateTime(dateString) {
  try {
    // Parse the input date string
    const date = new Date(dateString);

    // Check if the date is valid
    if (isNaN(date.getTime())) {
      throw new Error("Invalid date");
    }

    // Extract the day, month, year, hours, and minutes
    const day = date.getDate();
    const month = date.toLocaleString("default", { month: "short" }); // 3-letter month
    const year = date.getFullYear();
    const hours = date.getHours();
    const minutes = date.getMinutes().toString().padStart(2, "0"); // Ensure 2-digit minutes

    // Return the formatted date and time string
    return `${month} ${day}, ${year} `;
  } catch (error) {
    // console.error("Error formatting date:", error.message);
    return "Invalid date";
  }
}

export function formatDate(dateString) {
  try {
    // Parse the input date string
    const date = new Date(dateString);

    // Check if the date is valid
    if (isNaN(date.getTime())) {
      throw new Error("Invalid date");
    }

    // Extract the day, month, year, hours, and minutes
    const day = date.getDate();
    const month = date.toLocaleString("default", { month: "short" }); // 3-letter month
    const year = date.getFullYear();

    // Return the formatted date and time string
    return `${month} ${day}, ${year}`;
  } catch (error) {
    // console.error("Error formatting date:", error.message);
    return "Invalid date";
  }
}
// =================================================
export const financialYearConfig = {
  getCurrentFinancialYear: () => {
    const today = new Date();
    const currentMonth = today.getMonth() + 1; // JavaScript months are 0-based
    const currentYear = today.getFullYear();

    // If we're between January and March, we're in the previous year's fiscal year
    // Otherwise we're in the current year's fiscal year
    return currentMonth <= 3 ? currentYear - 1 : currentYear;
  },
  currentYear: function () {
    return this.getCurrentFinancialYear();
  },
};

export const greenBorderStyle = {
  "& .MuiOutlinedInput-root": {
    "& fieldset": {
      borderColor: "green",
    },
    "&:hover fieldset": {
      borderColor: "green",
    },
    "&.Mui-focused fieldset": {
      borderColor: "green",
    },
  },
  "& .MuiInputLabel-root": {
    color: "green",
    "&.Mui-focused": {
      color: "darkgreen",
    },
  },
  "& .MuiFormControlLabel-root": {
    color: "green",
    "&.Mui-checked": {
      color: "darkgreen",
    },
  },
  "& .MuiSelect-root": {
    "& fieldset": {
      borderColor: "green",
    },
    "&:hover fieldset": {
      borderColor: "green",
    },
    "&.Mui-focused fieldset": {
      borderColor: "green",
    },
  },
  "& .MuiRadio-root": {
    color: "green",
    "&.Mui-checked": {
      color: "darkgreen",
    },
  },
  "& .MuiCheckbox-root": {
    color: "green",
    "&.Mui-checked": {
      color: "green",
    },
  },
  "& .MuiFormLabel-root": {
    color: "darkgreen",
    "&.Mui-focused": {
      color: "darkgreen",
    },
  },
};

// const arr = {
//   BillCode: "INVP",
//   ReceiptDate: "2025-07-17T00:00:00",
//   PaymentType: "F",
//   QuotationNo: null,
//   ReceiptProductModelList: [
//     {
//       ProductModelID: "1",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "2",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "3",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "4",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "5",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },

//     {
//       ProductModelID: "6",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },

//     {
//       ProductModelID: "7",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "8",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "9",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "10",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "11",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "12",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "13",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "14",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "15",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "16",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "17",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "18",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "19",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "20",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },

//     {
//       ProductModelID: "21",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "22",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "23",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "24",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "25",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "26",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "27",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "28",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "29",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "30",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },

//     {
//       ProductModelID: "31",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "32",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "33",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "34",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "35",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "36",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "37",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "38",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "39",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "40",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "41",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "42",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "43",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "44",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "45",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "46",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "47",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "48",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "49",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "50",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "51",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//     {
//       ProductModelID: "52",
//       ColorMasterID: null,
//       HSNMasterID: null,
//       BrandMasterID: null,
//       CGSTP: "5",
//       SGSTP: "5",
//       Quantity: 0,
//       Unit: null,
//       Rate: 25,
//       DISP: 0,
//       Amount: 2750,
//       UnitQuantity: null,
//       QtyPerBox: null,
//       ExpiryDate: "2025-12-09T18:30:00.000Z",
//       MRP: "10",
//       StripOf: 10,
//       StripQty: 10,
//     },
//   ],

//   DiscountDesc: "",
//   DiscountUnit: "P",
//   BillEntityType: "COMP",
//   EntityType: "SUPP",
//   EntityID: "67",
//   BillEntityID: "58",
//   CheckedByID: "2",
//   PreparedByID: "2",
//   AuthorizedSignatoryByID: "2",
//   RoundOffAmount: 0,
//   customerProfileID: null,
//   custProStatus: "F",
//   DiscountAmount: 0,
//   TotalAmountAD: 0,
//   TotalAmountBD: 0,
//   CGSTAmount: 0,
//   SGSTAmount: 0,
//   GrandTotalAmount: 2750,
//   NetTotalAmount: 2500,
//   NetPaidAmount: 0,
//   NetDueAmount: 2750,
//   PaymentStatus: "Partial Due",
//   QuotationBookingMasterId: null,
//   Remarks: "",
// };
